spring.application.name=stream
api.server.panel = https://ratinhov5.sbs/player_api.php?username=34236517&password=83156563
api.server.movie = https://uexme.pics/movie/34236517/83156563/

server.tomcat.connection-timeout=120000
spring.mvc.async.request-timeout=0